[tool.poetry]
name = "iterable"
version = "0.1.0"
description = ""
authors = ["Omer <omer@whoppah.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.32.3"
ruff = "^0.6.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
